// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbgeVD1yGUDiMH9hFNqt0hXDBiY3vVnGQ',
    appId: '1:214583841692:web:cb6ac08e33a3133938ae59',
    messagingSenderId: '214583841692',
    projectId: 'announce-trumpet',
    authDomain: 'announce-trumpet.firebaseapp.com',
    storageBucket: 'announce-trumpet.appspot.com',
    measurementId: 'G-E982KMQVTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYodo1IYcsS5ZNaGe_9JsJYu-DUnWDuF0',
    appId: '1:214583841692:android:f0a0d07f2ceb8b5e38ae59',
    messagingSenderId: '214583841692',
    projectId: 'announce-trumpet',
    storageBucket: 'announce-trumpet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAdaKJ71oUUUX-6KkKl17aju8VmVtm2B0',
    appId: '1:214583841692:ios:c2f5022f7474802338ae59',
    messagingSenderId: '214583841692',
    projectId: 'announce-trumpet',
    storageBucket: 'announce-trumpet.appspot.com',
    iosClientId: '214583841692-2csg93mhvo4ffklcv3lqk5r39nujbrho.apps.googleusercontent.com',
    iosBundleId: 'com.willhuffman.trumpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAdaKJ71oUUUX-6KkKl17aju8VmVtm2B0',
    appId: '1:214583841692:ios:83985ab8ca7b731c38ae59',
    messagingSenderId: '214583841692',
    projectId: 'announce-trumpet',
    storageBucket: 'announce-trumpet.appspot.com',
    iosClientId: '214583841692-u5eegog5vgtoosgc3an6230ksls4suqc.apps.googleusercontent.com',
    iosBundleId: 'com.willhuffman.trumpet.RunnerTests',
  );
}
